services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: chiklati
      POSTGRES_PASSWORD: chiklati
      POSTGRES_DB: chiklati_bank
    ports:
      - "5433:5432"
    volumes:
      - chiklati_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chiklati -d chiklati_bank"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - chiklati_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  chiklati_postgres_data:
  chiklati_redis_data:
